/**
 * Seed referrals — one or more in every lifecycle state, built by replaying
 * the real workflow rather than written out by hand.
 *
 * Each scenario below is a list of actions by named users at named times.
 * Running them through lib/referrals/workflow.ts means every seeded timeline
 * is one the app itself could have produced: the right roles at the right
 * facilities, legal transitions only, notifications generated by the same
 * fan-out the live app uses. A scenario that breaks a rule throws here, and
 * scripts/verify-referral-flow.mts fails on it, instead of a demo record
 * quietly showing a state the app forbids.
 */

import { FACILITY_NETWORK, SEED_PATIENTS } from '@/lib/data/facilities';
import { SEED_USERS } from '@/lib/auth/users';
import {
    actorFromUser,
    addComment,
    applyAction,
    createReferral,
    notificationsFor,
    notificationsForComment,
    type ActionInput,
} from '@/lib/referrals/workflow';
import type { ReferralRecord } from '@/types/patient';
import type { NotificationRecord, RejectReasonCode } from '@/types/referral';
import type { WardType } from '@/types/resources';

const NOW = Date.now();
const iso = (minutesAgo: number) => new Date(NOW - minutesAgo * 60_000).toISOString();

function facilityRef(id: string) {
    const f = FACILITY_NETWORK.find(x => x.id === id);
    if (!f) throw new Error(`Seed referral names unknown facility ${id}`);
    return { id: f.id, name: f.name, type: f.type };
}

function actor(userId: string) {
    const u = SEED_USERS.find(x => x.id === userId);
    if (!u) throw new Error(`Seed referral names unknown user ${userId}`);
    return actorFromUser(u, u.facilityId ? facilityRef(u.facilityId).name : 'District Health Office');
}

type Step =
    | { do: 'SEND'; min: number; by: string }
    | { do: 'OPEN' | 'ACKNOWLEDGE' | 'MARK_ARRIVED' | 'ADMIT' | 'DISCHARGE'; min: number; by: string; note?: string }
    | { do: 'ACCEPT'; min: number; by: string; ward?: WardType; handover?: string }
    | { do: 'REJECT'; min: number; by: string; code: RejectReasonCode; detail?: string }
    | { do: 'DISPATCH'; min: number; by: string; vehicle?: string; eta?: number }
    | { do: 'TREATMENT_NOTE'; min: number; by: string; note: string }
    | { do: 'COMMENT'; min: number; by: string; text: string };

interface Scenario {
    id: string;
    patientId: string;
    from: string;
    to: string;
    by: string;
    min: number;
    priority: ReferralRecord['priority'];
    transport: ReferralRecord['transportMode'];
    reason: string;
    summary?: string;
    steps: Step[];
}

const WARD_NAME: Record<WardType, string> = {
    GENERAL: 'General',
    ICU: 'ICU',
    MATERNITY: 'Maternity',
    PEDIATRIC: 'Paediatric',
    EMERGENCY: 'Emergency',
};

const SCENARIOS: Scenario[] = [
    // ACCEPTED, bed held, patient in the ambulance.
    {
        id: 'ref-seed-01',
        patientId: 'p-gad-1001',
        from: 'sc-kothi',
        to: 'chc-etapalli',
        by: 'u-anm-kothi',
        min: 50,
        priority: 'EMERGENCY',
        transport: 'AMBULANCE_102',
        reason: 'Severe gestational hypertension (BP 160/102 at 32 weeks) with headache and blurred vision — CEmONC evaluation',
        summary: 'Primigravida 32 weeks. Pedal oedema ++, brisk reflexes. Labetalol 100 mg given per MO teleconsult.',
        steps: [
            { do: 'SEND', min: 50, by: 'u-anm-kothi' },
            { do: 'OPEN', min: 47, by: 'u-ha-chc' },
            { do: 'ACKNOWLEDGE', min: 46, by: 'u-ha-chc' },
            { do: 'ACCEPT', min: 44, by: 'u-ha-chc', ward: 'MATERNITY', handover: 'Labour room, ground floor. Bring ANC card and referral slip; call +91-7133-264100 on departure.' },
            { do: 'COMMENT', min: 43, by: 'u-ha-chc', text: 'Maternity bed 4 held. OT and eclampsia tray being readied.' },
            { do: 'DISPATCH', min: 40, by: 'u-anm-kothi', vehicle: 'AMB-T-0102', eta: 35 },
            { do: 'COMMENT', min: 39, by: 'u-anm-kothi', text: 'Left with 102. BP 158/100 at departure, patient alert.' },
        ],
    },
    // ADMITTED at the District Hospital, with a specialist's note.
    {
        id: 'ref-seed-02',
        patientId: 'p-gad-1003',
        from: 'phc-perimili',
        to: 'dh-district',
        by: 'u-mo-perimili',
        min: 180,
        priority: 'EMERGENCY',
        transport: 'AMBULANCE_108',
        reason: 'Severe acute malnutrition with respiratory distress (SpO2 91%, RR 48/min) — SNCU/NRC care',
        summary: 'Chest indrawing, fever 102.4 F. Oxygen by nasal cannula at 2 L/min started.',
        steps: [
            { do: 'SEND', min: 180, by: 'u-mo-perimili' },
            { do: 'OPEN', min: 176, by: 'u-ha-dh' },
            { do: 'ACKNOWLEDGE', min: 175, by: 'u-ha-dh' },
            { do: 'ACCEPT', min: 172, by: 'u-ha-dh', ward: 'PEDIATRIC', handover: 'Paediatric emergency, block B. Keep oxygen running in transit.' },
            { do: 'DISPATCH', min: 168, by: 'u-mo-perimili', vehicle: 'AMB-E-1081', eta: 90 },
            { do: 'MARK_ARRIVED', min: 80, by: 'u-ha-dh' },
            { do: 'ADMIT', min: 72, by: 'u-ha-dh' },
            { do: 'TREATMENT_NOTE', min: 50, by: 'u-sp-dh', note: 'Started on F-75 feeds and IV antibiotics per SAM protocol. SpO2 95% on 1 L oxygen.' },
        ],
    },
    // DELIVERED — opened by the CHC, not yet answered. The CHC's X-ray is out
    // of order, so the capacity check shows a real shortfall.
    {
        id: 'ref-seed-03',
        patientId: 'p-gad-1002',
        from: 'phc-bhamragad',
        to: 'chc-etapalli',
        by: 'u-mo-bhamragad',
        min: 75,
        priority: 'URGENT',
        transport: 'SELF',
        reason: 'Uncontrolled diabetes with grade-2 plantar ulcer needing surgical debridement and X-ray',
        summary: 'Random glucose 284 mg/dL. Ulcer 3×2 cm with slough. Dressing done, amoxiclav started.',
        steps: [
            { do: 'SEND', min: 75, by: 'u-mo-bhamragad' },
            { do: 'OPEN', min: 30, by: 'u-ha-chc' },
        ],
    },
    // ACCEPTED as outpatient work — no bed needed.
    {
        id: 'ref-seed-04',
        patientId: 'p-gad-1004',
        from: 'phc-bhamragad',
        to: 'dh-district',
        by: 'u-mo-bhamragad',
        min: 26 * 60,
        priority: 'ROUTINE',
        transport: 'PUBLIC_TRANSPORT',
        reason: 'Follow-up sputum CBNAAT test for pulmonary TB, month 3',
        steps: [
            { do: 'SEND', min: 26 * 60, by: 'u-mo-bhamragad' },
            { do: 'OPEN', min: 25 * 60, by: 'u-ha-dh' },
            { do: 'ACCEPT', min: 25 * 60 - 5, by: 'u-ha-dh' },
        ],
    },
    // SENT, Emergency, unacknowledged for 12 minutes — the escalation clock
    // alerts the DHO on the first sweep after the app opens.
    {
        id: 'ref-seed-05',
        patientId: 'p-gad-1006',
        from: 'sc-govindpur',
        to: 'phc-bhamragad',
        by: 'u-anm-govindpur',
        min: 12,
        priority: 'EMERGENCY',
        transport: 'AMBULANCE_108',
        reason: 'Snake bite (suspected krait) 40 min ago — early ptosis, abdominal pain. Needs ASV and airway watch.',
        summary: 'Bitten while asleep on the floor. Limb immobilised. No tourniquet.',
        steps: [{ do: 'SEND', min: 12, by: 'u-anm-govindpur' }],
    },
    // ACKNOWLEDGED by the PHC, decision pending.
    {
        id: 'ref-seed-06',
        patientId: 'p-gad-1007',
        from: 'sc-kothi',
        to: 'phc-bhamragad',
        by: 'u-anm-kothi',
        min: 40,
        priority: 'URGENT',
        transport: 'SELF',
        reason: 'Falciparum malaria (RDT positive), fever 5 days, repeated vomiting — cannot retain oral ACT',
        steps: [
            { do: 'SEND', min: 40, by: 'u-anm-kothi' },
            { do: 'OPEN', min: 25, by: 'u-mo-bhamragad' },
            { do: 'ACKNOWLEDGE', min: 24, by: 'u-mo-bhamragad' },
            { do: 'COMMENT', min: 23, by: 'u-mo-bhamragad', text: 'Checking a general bed — will confirm in 10 minutes.' },
        ],
    },
    // REJECTED — the CHC's X-ray is down; the PHC must re-route.
    {
        id: 'ref-seed-07',
        patientId: 'p-gad-1008',
        from: 'phc-perimili',
        to: 'chc-etapalli',
        by: 'u-mo-perimili',
        min: 140,
        priority: 'EMERGENCY',
        transport: 'AMBULANCE_108',
        reason: 'Road traffic accident — closed fracture right tibia with deformity; needs X-ray and orthopaedic care',
        steps: [
            { do: 'SEND', min: 140, by: 'u-mo-perimili' },
            { do: 'OPEN', min: 137, by: 'u-ha-chc' },
            { do: 'REJECT', min: 135, by: 'u-ha-chc', code: 'EQUIPMENT_MAINTENANCE', detail: 'X-ray out of order until repair; no orthopaedic surgeon on duty' },
        ],
    },
    // DISCHARGED — the full cycle, two days ago.
    {
        id: 'ref-seed-08',
        patientId: 'p-gad-1009',
        from: 'sc-govindpur',
        to: 'phc-bhamragad',
        by: 'u-anm-govindpur',
        min: 2880,
        priority: 'URGENT',
        transport: 'SELF',
        reason: 'Acute gastroenteritis with moderate dehydration — IV fluids',
        steps: [
            { do: 'SEND', min: 2880, by: 'u-anm-govindpur' },
            { do: 'OPEN', min: 2876, by: 'u-mo-bhamragad' },
            { do: 'ACKNOWLEDGE', min: 2875, by: 'u-mo-bhamragad' },
            { do: 'ACCEPT', min: 2874, by: 'u-mo-bhamragad', ward: 'GENERAL', handover: 'PHC ward, bed 2.' },
            { do: 'DISPATCH', min: 2873, by: 'u-anm-govindpur', eta: 40 },
            { do: 'MARK_ARRIVED', min: 2830, by: 'u-mo-bhamragad' },
            { do: 'ADMIT', min: 2825, by: 'u-mo-bhamragad' },
            { do: 'TREATMENT_NOTE', min: 2820, by: 'u-mo-bhamragad', note: '2 L Ringer lactate, ORS. Tolerating orally by evening.' },
            { do: 'DISCHARGE', min: 1440, by: 'u-mo-bhamragad', note: 'Hydrated, stools settled. ANM follow-up in 2 days.' },
        ],
    },
    // PATIENT_ARRIVED at the DH, awaiting admission to the held ICU bed.
    {
        id: 'ref-seed-09',
        patientId: 'p-gad-1010',
        from: 'phc-bhamragad',
        to: 'dh-district',
        by: 'u-mo-bhamragad',
        min: 150,
        priority: 'EMERGENCY',
        transport: 'AMBULANCE_108',
        reason: 'Suspected acute myocardial infarction — central chest pain 2 h, ST elevation V2–V4',
        summary: 'Aspirin 325 mg chewed. SpO2 93% on air.',
        steps: [
            { do: 'SEND', min: 150, by: 'u-mo-bhamragad' },
            { do: 'OPEN', min: 147, by: 'u-ha-dh' },
            { do: 'ACKNOWLEDGE', min: 146, by: 'u-ha-dh' },
            { do: 'ACCEPT', min: 145, by: 'u-ha-dh', ward: 'ICU', handover: 'ICU, first floor. Cardiology on call informed.' },
            { do: 'DISPATCH', min: 140, by: 'u-mo-bhamragad', vehicle: 'AMB-E-1084', eta: 120 },
            { do: 'MARK_ARRIVED', min: 10, by: 'u-ha-dh' },
        ],
    },
    // ACCEPTED 3 h 52 min ago and never dispatched — the bed hold runs out a
    // few minutes after the app opens, and the clock releases it.
    {
        id: 'ref-seed-10',
        patientId: 'p-gad-1011',
        from: 'phc-perimili',
        to: 'sdh-aheri',
        by: 'u-mo-perimili',
        min: 4 * 60,
        priority: 'URGENT',
        transport: 'SELF',
        reason: 'Severe anaemia (Hb 5.8 g/dL) with breathlessness — transfusion',
        steps: [
            { do: 'SEND', min: 4 * 60, by: 'u-mo-perimili' },
            { do: 'OPEN', min: 4 * 60 - 4, by: 'u-ha-sdh' },
            { do: 'ACCEPT', min: 3 * 60 + 52, by: 'u-ha-sdh', ward: 'GENERAL', handover: 'Female ward, SDH. Blood grouped on arrival.' },
            { do: 'COMMENT', min: 3 * 60 + 40, by: 'u-mo-perimili', text: 'Family arranging a vehicle — will confirm departure.' },
        ],
    },
];

function build(s: Scenario): { referral: ReferralRecord; notifications: NotificationRecord[] } {
    const patient = SEED_PATIENTS.find(p => p.id === s.patientId);
    if (!patient) throw new Error(`Seed referral ${s.id} names unknown patient ${s.patientId}`);

    const created = createReferral(
        {
            id: s.id,
            eventId: `${s.id}:create`,
            at: iso(s.min),
            patient: { id: patient.id, name: patient.name, age: patient.age, gender: patient.gender },
            from: facilityRef(s.from),
            to: facilityRef(s.to),
            reason: s.reason,
            priority: s.priority,
            transportMode: s.transport,
            clinicalSummary: s.summary,
            vitals: patient.vitals,
        },
        actor(s.by)
    );
    if (!created.ok) throw new Error(`Seed referral ${s.id}: ${created.message}`);

    let referral = created.referral;
    const notifications: NotificationRecord[] = [];

    s.steps.forEach((step, i) => {
        const at = iso(step.min);
        const eventId = `${s.id}:${i}:${step.do.toLowerCase()}`;
        if (step.do === 'COMMENT') {
            const r = addComment(referral, actor(step.by), step.text, at, eventId);
            if (!r.ok) throw new Error(`Seed referral ${s.id} comment: ${r.message}`);
            referral = r.referral;
            notifications.push(...notificationsForComment(referral, r.comment, SEED_USERS));
            return;
        }
        const input: ActionInput = { action: step.do, actor: actor(step.by), at, eventId };
        if (step.do === 'SEND') input.sentVia = 'RELAY';
        if ('note' in step && step.note) input.note = step.note;
        if (step.do === 'ACCEPT' && step.ward) {
            input.reservation = {
                ward: step.ward,
                label: `${WARD_NAME[step.ward]} ward bed`,
                handoverInstructions: step.handover ?? '',
            };
        }
        if (step.do === 'REJECT') input.reject = { code: step.code, detail: step.detail };
        if (step.do === 'DISPATCH') input.dispatch = { vehicleNo: step.vehicle, etaMinutes: step.eta };

        const r = applyAction(referral, input);
        if (!r.ok) throw new Error(`Seed referral ${s.id} step ${step.do}: ${r.message}`);
        referral = r.referral;
        notifications.push(...notificationsFor(referral, r.event, SEED_USERS));
    });

    return { referral, notifications };
}

const built = SCENARIOS.map(build);

export const SEED_REFERRALS: ReferralRecord[] = built.map(b => b.referral);

/**
 * Notifications the seeded history would have produced. Anything older than
 * 20 minutes is marked read, so the bell opens on what is actually recent.
 */
export const SEED_NOTIFICATIONS: NotificationRecord[] = built
    .flatMap(b => b.notifications)
    .map(n => ({ ...n, is_read: NOW - Date.parse(n.created_at) > 20 * 60_000 }));
