/**
 * Write the Android app's cleartext allow-list for this build — run before
 * `npx cap sync android` (`npm run android:network-config`).
 *
 * A facility's relay and district service run on its own LAN over plain HTTP.
 * Android refuses cleartext unless the host is listed, and it matches hostnames
 * exactly — an entry like "192.168.0.0" never covered 192.168.1.9, so the APK
 * could not reach its relay at all. This reads the hosts baked into the build
 * (NEXT_PUBLIC_MESH_URL, NEXT_PUBLIC_REPORTING_URL) and allows exactly those,
 * plus localhost and the emulator's host alias. Every other host still needs TLS.
 */

import { writeFileSync } from 'node:fs';

const hosts = new Set<string>(['localhost', '10.0.2.2']);
const skipped: string[] = [];
for (const name of ['NEXT_PUBLIC_MESH_URL', 'NEXT_PUBLIC_REPORTING_URL'] as const) {
    const value = process.env[name]?.trim();
    if (!value) continue;
    const url = new URL(value);
    if (url.protocol === 'http:') hosts.add(url.hostname);
    else skipped.push(`${name} (${url.protocol} needs no exception)`);
}

const xml = `<?xml version="1.0" encoding="utf-8"?>
<!--
    GENERATED by scripts/android-network-config.mts for this build — edit the
    build's NEXT_PUBLIC_MESH_URL / NEXT_PUBLIC_REPORTING_URL, not this file.

    Plain HTTP is allowed only to the hosts this build talks to on the facility
    LAN (Android matches hostnames exactly; IP ranges are not supported).
    Every other host requires TLS.
-->
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
${[...hosts].map(h => `        <domain includeSubdomains="false">${h}</domain>`).join('\n')}
    </domain-config>
    <base-config cleartextTrafficPermitted="false">
        <trust-anchors>
            <certificates src="system" />
        </trust-anchors>
    </base-config>
</network-security-config>
`;

writeFileSync(new URL('../android/app/src/main/res/xml/network_security_config.xml', import.meta.url), xml);
console.log(`Cleartext allowed to: ${[...hosts].join(', ')}${skipped.length ? `; skipped ${skipped.join(', ')}` : ''}`);
